version: '3.3'

services:
  back:
    container_name: geo-prod
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python manage.py makemigrations && python manage.py sqlmigrate contries 0001 && python manage.py migrate && python manage.py collectstatic
      --no-input && python ./manage.py shell < from contries import load < load.run()"
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - .:/opt/services/geo-prod
      - ./static/static_data:/opt/services/geo-prod/static
      - ./static/media_data:/opt/services/geo-prod/back_media
    networks:
      - nginx_network
      - db_network
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:14-alpine
    container_name: geodjango
    restart: always
    networks:
      - db_network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD='geopass'
      - POSTGRES_DB='geodjango'
      - PGPORT='localhost'
      - POSTGRES_USER='geo'

volumes:
  postgres_data:
networks:
  db_network:
    driver: bridge